title: Junghoon Choi
description: > # this means to ignore newlines until "baseurl:"
  Senior Developer at XREAL
permalink: ":title/"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://be9904.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Junghoon Choi # add your name
author-img: bruni-sq.jpg # add your photo
about-author: Senior Developer at <a href="https://www.xreal.info/" target="_blank">XREAL</a> # add description
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: be9904 # add your Github handle
social-linkedin: cjhoon # add your Linkedin handle
social-email: be9904@gmail.com # add your Email address

# Disqus
disqus:
  shortname: "be9904" # disqus short name, https://help.disqus.com/en/articles/1717111-what-s-a-shortname

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-spaceship

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
